version: '3'
services:
  backend:
    build: ./
    container_name: backend
    restart: always
    environment:
      - TOKEN_EXP=1000
      - PRIVATE_KEY=kljasdlfaldjflakdsfjladsfjalsdkfjlasdfjkaldsfkj
      - MONGO_USERNAME=shashankp28
      - MONGO_PASSWORD=U17sGoyF9mFP0tSn
    ports:
      - '8040:8000'
